#!/bin/sh
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

## Autostart Stuff
swaybg -i /usr/share/backgrounds/mountain01.jpg &
waybar &
pipewire &
swayidle &
hyperx-volume-wheel-fix-rs &
wlsunset -l 48 -L 14 &
nm-applet &

## set keyboard layout
riverctl keyboard-layout -variant ,bone -options "grp:ctrl_space_toggle" de,de

riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad tap enabled


# open daily notes
riverctl map normal Super N spawn 'alacritty -e dailynotes.sh'


## lock screen
riverctl map normal Super L spawn 'waylock-styled'

## start terminal 
riverctl map normal Super Return spawn alacritty

## start app-launcher
riverctl map normal Super D spawn 'tofi-drun | xargs -d \" riverctl spawn'

# close window
riverctl map normal Super Q close

# quit riverwm
riverctl map normal Super M exit

# screnshot of are
riverctl map normal Super+Shift S spawn "slurp | grim -g - - | wl-copy -t image/png"


# switch focused window
riverctl map normal Super Right focus-view next
riverctl map normal Super Left focus-view previous
riverctl map normal Super Down focus-view next
riverctl map normal Super Up focus-view previous

# swap focused window
riverctl map normal Super+Shift Right swap next
riverctl map normal Super+Shift Left swap previous

# MULTIHEAD
# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# MULTIHEAD
# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Currently Unused
# Super+Return to bump the focused view to the top of the layout stack
# riverctl map normal Super+Control F zoom

# Change Main/Secondary RATIO
riverctl map normal Super+Control Left send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Control Right send-layout-cmd rivertile "main-ratio +0.05"


## FLOATING OPTIONS
# Move Floating Window
riverctl map normal Super+Alt Left move left 100
riverctl map normal Super+Alt Down move down 100
riverctl map normal Super+Alt Up move up 100
riverctl map normal Super+Alt Right move right 100

# Resize Floating Window
riverctl map normal Super+Alt+Shift Left resize horizontal -100
riverctl map normal Super+Alt+Shift Up resize vertical 100
riverctl map normal Super+Alt+Shift Down resize vertical -100
riverctl map normal Super+Alt+Shift Right resize horizontal 100

# MOUSE OPTIONS
# drag window
riverctl map-pointer normal Super BTN_LEFT move-view
# resize window
riverctl map-pointer normal Super BTN_RIGHT resize-view
# toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float


# Workspace Options
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # dont understand, sorry :(
    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    # riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# 1. throw all windows on workspace 0
# 2. pin a window to all workspaces (workspace 0)
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# toggle float
riverctl map normal Super Space toggle-float

# toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Maybe i could use this?
# Super+{Up,Right,Down,Left} to change layout orientation
#riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
#riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
#riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
#riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# EXAMPLES: CHECK ME OR MODIFY ME, IDK
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

# Set background and border color
riverctl background-color 0x282828
riverctl border-color-focused 0xd79921
riverctl border-color-unfocused 0x928374
riverctl border-color-urgent 0xcc241d
riverctl border-width 4

# Set keyboard repeat rate
riverctl set-repeat 100 300


# MAYBE I CAN USE THIS? COOL FEATURE!
# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float
# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 4 &

exec dbus-update-activation-environment DISPLAY I3SOCK SWAYSOCK WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river

